# Generated by Django 2.2.3 on 2023-01-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Слово')),
                ('translation', models.CharField(max_length=128, verbose_name='Перевод')),
                ('right_answer', models.IntegerField(default=0, verbose_name='Правильный ответ')),
                ('wrong_answer', models.IntegerField(default=0, verbose_name='Неправильный ответ')),
                ('type', models.CharField(choices=[('noun', 'Существительное'), ('adjective', 'Прилагательное'), ('verb', 'Глагол'), ('phrase', 'Фраза')], default='noun', max_length=64, verbose_name='Тип')),
                ('wrong_form', models.CharField(blank=True, max_length=64, null=True, verbose_name='Неправильная форма')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
