# Generated by Django 2.2.3 on 2023-01-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_language', '0002_auto_20230128_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(choices=[('noun', 'Существительное'), ('adjective', 'Прилагательное'), ('verb', 'Глагол'), ('adverb', 'Наречие'), ('phrase', 'Фраза')], default='noun', max_length=64, verbose_name='Тип'),
        ),
    ]
