# Generated by Django 2.2.3 on 2023-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_language', '0003_auto_20230130_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='right_answer',
        ),
        migrations.RemoveField(
            model_name='word',
            name='wrong_answer',
        ),
        migrations.AddField(
            model_name='word',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
