# Generated by Django 2.2.3 on 2023-01-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_language', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='wrong_form',
        ),
        migrations.AddField(
            model_name='word',
            name='past_form',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Прошедшая форма'),
        ),
    ]
